@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package arc.bloodarsenal.compat.baubles;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;