package com.arc.bloodarsenal.items;

import WayofTime.alchemicalWizardry.AlchemicalWizardry;
import com.arc.bloodarsenal.BloodArsenal;
import com.arc.bloodarsenal.block.ModBlocks;
import com.arc.bloodarsenal.items.armor.VampireCostume;
import com.arc.bloodarsenal.items.bauble.SacrificeAmulet;
import com.arc.bloodarsenal.items.bauble.SelfSacrificeAmulet;
import com.arc.bloodarsenal.items.bauble.VampireRing;
import com.arc.bloodarsenal.items.block.*;
import com.arc.bloodarsenal.items.sigil.SigilDivinity;
import com.arc.bloodarsenal.items.sigil.SigilEnder;
import com.arc.bloodarsenal.items.sigil.SigilSwimming;
import com.arc.bloodarsenal.items.tool.*;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.material.Material;
import net.minecraft.item.Item;
import net.minecraft.item.ItemReed;

public class ModItems
{
    public static Item bound_bow;
    public static Item blood_orange;
    public static Item blood_infused_pickaxe_wood;
    public static Item blood_infused_axe_wood;
    public static Item blood_infused_shovel_wood;
    public static Item blood_infused_sword_wood;
    public static Item amorphic_catalyst;
    public static Item blood_infused_stick;
    public static Item bound_sickle;
    public static Item blood_infused_pickaxe_iron;
    public static Item blood_infused_axe_iron;
    public static Item blood_infused_shovel_iron;
    public static Item blood_infused_sword_iron;
    public static Item blood_infused_iron;
    public static Item bound_shears;
    public static Item blood_diamond;
    public static Item blood_infused_diamond_unactive;
    public static Item blood_infused_diamond_active;
    public static Item blood_infused_diamond_bound;
    public static Item blood_infused_pickaxe_diamond;
    public static Item blood_infused_axe_diamond;
    public static Item blood_infused_shovel_diamond;
    public static Item blood_infused_sword_diamond;
    public static Item heart;
    public static Item soul_fragment;
    public static Item item_blood_door_wood;
    public static Item item_blood_door_iron;
    public static Item bound_igniter;
    public static Item soul_booster;
    public static Item soul_nullifier;
    public static Item blood_cookie;
    public static Item orange_juice;
    public static Item juice_and_cookies;
    public static Item item_blood_cake;
    public static Item vampire_cape;
    public static Item vampire_greaves;
    public static Item vampire_boots;
    public static Item vampire_ring;
    public static Item energy_gatling;
    public static Item sigil_of_swimming;
    public static Item sigil_of_ender;
    public static Item blood_infused_glowstone_dust;
    public static Item self_sacrifice_amulet;
    public static Item sacrifice_amulet;
    public static Item sigil_of_divinity;
    public static Item blood_ball;
    public static Item wolf_hide;
    public static Item blood_money;
    public static Item blood_burned_string;

    public static void init()
    {
        bound_bow = new BoundBow();
        blood_orange = new ItemBloodOrange();
        blood_infused_pickaxe_wood = new InfusedWoodPickaxe();
        blood_infused_axe_wood = new InfusedWoodAxe();
        blood_infused_shovel_wood = new InfusedWoodShovel();
        blood_infused_sword_wood = new InfusedWoodSword();
        amorphic_catalyst = new ItemBloodArsenal().setUnlocalizedName("amorphic_catalyst");
        blood_infused_stick = new ItemBloodArsenal().setUnlocalizedName("blood_infused_stick");
        bound_sickle = new BoundSickle(AlchemicalWizardry.bloodBoundToolMaterial);
        blood_infused_pickaxe_iron = new InfusedIronPickaxe();
        blood_infused_axe_iron = new InfusedIronAxe();
        blood_infused_shovel_iron = new InfusedIronShovel();
        blood_infused_sword_iron = new InfusedIronSword();
        blood_infused_iron = new ItemBloodArsenal().setUnlocalizedName("blood_infused_iron");
        bound_shears = new BoundShears();
        blood_diamond = new InfusedDiamond().setUnlocalizedName("blood_diamond");
        blood_infused_diamond_unactive = new InfusedDiamond().setUnlocalizedName("blood_infused_diamond_unactive");
        blood_infused_diamond_active = new InfusedDiamond().setUnlocalizedName("blood_infused_diamond_active");
        blood_infused_diamond_bound = new InfusedDiamond().setUnlocalizedName("blood_infused_diamond_bound");
        blood_infused_pickaxe_diamond = new InfusedDiamondPickaxe();
        blood_infused_axe_diamond = new InfusedDiamondAxe();
        blood_infused_shovel_diamond = new InfusedDiamondShovel();
        blood_infused_sword_diamond = new InfusedDiamondSword();
        heart = new ItemBloodArsenal().setUnlocalizedName("heart");
        soul_fragment = new ItemBloodArsenal().setUnlocalizedName("soul_fragment");
        item_blood_door_wood = new BloodDoor(Material.wood).setUnlocalizedName("item_blood_door_wood").setTextureName("BloodArsenal:item_blood_door_wood");
        item_blood_door_iron = new BloodDoor(Material.iron).setUnlocalizedName("item_blood_door_iron").setTextureName("BloodArsenal:item_blood_door_iron");
        bound_igniter = new BoundIgniter();
        soul_booster = new ItemSoulBooster();
        soul_nullifier = new ItemSoulNullifier();
        blood_cookie = new ItemBloodCookie();
        orange_juice = new ItemBloodArsenal().setUnlocalizedName("orange_juice");
        juice_and_cookies = new ItemJuiceAndCookies();
        item_blood_cake = new ItemReed(ModBlocks.blood_cake).setUnlocalizedName("item_blood_cake").setTextureName("BloodArsenal:item_blood_cake").setCreativeTab(BloodArsenal.BA_TAB);
        vampire_cape = new VampireCostume(1).setUnlocalizedName("vampire_cape");
        vampire_greaves = new VampireCostume(2).setUnlocalizedName("vampire_greaves");
        vampire_boots = new VampireCostume(3).setUnlocalizedName("vampire_boots");
        energy_gatling = new EnergyGatling();
        sigil_of_swimming = new SigilSwimming();
        sigil_of_ender = new SigilEnder();
        blood_infused_glowstone_dust = new ItemBloodArsenal().setUnlocalizedName("blood_infused_glowstone_dust");
        sigil_of_divinity = new SigilDivinity();
        blood_ball = new ItemBloodBall();
        wolf_hide = new ItemBloodArsenal().setUnlocalizedName("wolf_hide");
        blood_money = new ItemBloodMoney();
        blood_burned_string = new ItemBloodArsenal().setUnlocalizedName("blood_burned_string");
        vampire_ring = new VampireRing();
        self_sacrifice_amulet = new SelfSacrificeAmulet();
        sacrifice_amulet = new SacrificeAmulet();
    }

    public static void registerItems()
    {
        GameRegistry.registerItem(bound_bow, "bound_bow");
        GameRegistry.registerItem(blood_orange, "blood_orange");
        GameRegistry.registerItem(blood_infused_pickaxe_wood, "blood_infused_pickaxe_wood");
        GameRegistry.registerItem(blood_infused_axe_wood, "blood_infused_axe_wood");
        GameRegistry.registerItem(blood_infused_shovel_wood, "blood_infused_shovel_wood");
        GameRegistry.registerItem(blood_infused_sword_wood, "blood_infused_sword_wood");
        GameRegistry.registerItem(amorphic_catalyst, "amorphic_catalyst");
        GameRegistry.registerItem(blood_infused_stick, "blood_infused_stick");
        GameRegistry.registerItem(bound_sickle, "bound_sickle");
        GameRegistry.registerItem(blood_infused_pickaxe_iron, "blood_infused_pickaxe_iron");
        GameRegistry.registerItem(blood_infused_axe_iron, "blood_infused_axe_iron");
        GameRegistry.registerItem(blood_infused_shovel_iron, "blood_infused_shovel_iron");
        GameRegistry.registerItem(blood_infused_sword_iron, "blood_infused_sword_iron");
        GameRegistry.registerItem(blood_infused_iron, "blood_infused_iron");
        GameRegistry.registerItem(bound_shears, "bound_shears");
        GameRegistry.registerItem(blood_diamond, "blood_diamond");
        GameRegistry.registerItem(blood_infused_diamond_unactive, "blood_infused_diamond_unactive");
        GameRegistry.registerItem(blood_infused_diamond_active, "blood_infused_diamond_active");
        GameRegistry.registerItem(blood_infused_diamond_bound, "blood_infused_diamond_bound");
        GameRegistry.registerItem(blood_infused_pickaxe_diamond, "blood_infused_pickaxe_diamond");
        GameRegistry.registerItem(blood_infused_axe_diamond, "blood_infused_axe_diamond");
        GameRegistry.registerItem(blood_infused_shovel_diamond, "blood_infused_shovel_diamond");
        GameRegistry.registerItem(blood_infused_sword_diamond, "blood_infused_sword_diamond");
        GameRegistry.registerItem(heart, "heart");
        GameRegistry.registerItem(soul_fragment, "soul_fragment");
        GameRegistry.registerItem(item_blood_door_wood, "item_blood_door_wood");
        GameRegistry.registerItem(item_blood_door_iron, "item_blood_door_iron");
        GameRegistry.registerItem(item_blood_cake, "item_blood_cake");
        GameRegistry.registerItem(bound_igniter, "bound_flint_and_steel");
        GameRegistry.registerItem(soul_booster, "soul_booster");
        GameRegistry.registerItem(soul_nullifier, "soul_nullfier");
        GameRegistry.registerItem(blood_cookie, "blood_cookie");
        GameRegistry.registerItem(orange_juice, "orange_juice");
        GameRegistry.registerItem(juice_and_cookies, "juice_and_cookies");
        GameRegistry.registerItem(vampire_cape, "vampire_cape");
        GameRegistry.registerItem(vampire_greaves, "vampire_greaves");
        GameRegistry.registerItem(vampire_boots, "vampire_boots");
        GameRegistry.registerItem(energy_gatling, "energy_gatling");
        GameRegistry.registerItem(sigil_of_swimming, "sigil_of_swimming");
        GameRegistry.registerItem(sigil_of_ender, "sigil_of_ender");
        GameRegistry.registerItem(blood_infused_glowstone_dust, "blood_infused_glowstone_dust");
        GameRegistry.registerItem(sigil_of_divinity, "sigil_of_divinity");
        GameRegistry.registerItem(blood_ball, "blood_ball");
        GameRegistry.registerItem(wolf_hide, "wolf_hide");
        GameRegistry.registerItem(blood_money, "blood_money");
        GameRegistry.registerItem(blood_burned_string, "blood_burned_string");
    }
}
