@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package arc.bloodarsenal.compat.guideapi;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;